### ISSUE TITLE
Connector tasks entering failed state

### ISSUE THREAD

**Issue by gdooper** [Azure/toketi-kafka-connect-iothub#12]
I've been working with this connector for a few months now. Recently we've noticed in our staging environment that some of the connector tasks were entering a failed state.

Here are a few failed connector tasks that I've seen. This first one says **Exception - com.microsoft.azure.servicebus.ServiceBusException: The message container is being closed (428).**
```js
{
  "name": "uploadnotifications_in",
  "connector": {
    "state": "RUNNING",
    "worker_id": "connect-2.connect:28082"
  },
  "tasks": [
    {
      "state": "RUNNING",
      "id": 0,
      "worker_id": "connect-0.connect:28082"
    },
    {
      "state": "FAILED",
      "trace": "org.apache.kafka.connect.errors.ConnectException: Error while polling for data at com.microsoft.azure.iot.kafka.connect.source.IotHubSourceTask.poll(IotHubSourceTask.scala:37) at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: org.apache.kafka.connect.errors.ConnectException: Error while getting SourceRecords for partition 1. Exception - com.microsoft.azure.servicebus.ServiceBusException: The message container is being closed (428). TrackingId:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_B24, SystemTracker:NoSystemTracker, Timestamp:12/18/2017 10:44:58 AM, errorContext[NS: xxxxxxxxxx.servicebus.windows.net, PATH: uploadnotifications/ConsumerGroups/kafka-cg/Partitions/1, REFERENCE_ID: xxxxxx_xxx_xxx_xxxxxxxxxxxxx, PREFETCH_COUNT: 999, LINK_CREDIT: 999, PREFETCH_Q_LEN: 0] Stack trace - () at com.microsoft.azure.iot.kafka.connect.source.IotHubPartitionSource.getRecords(IotHubPartitionSource.scala:51) at com.microsoft.azure.iot.kafka.connect.source.IotHubSourceTask$$anonfun$poll$1.apply(IotHubSourceTask.scala:30) at com.microsoft.azure.iot.kafka.connect.source.IotHubSourceTask$$anonfun$poll$1.apply(IotHubSourceTask.scala:28) at scala.collection.immutable.List.foreach(List.scala:381) at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45) at com.microsoft.azure.iot.kafka.connect.source.IotHubSourceTask.poll(IotHubSourceTask.scala:28) ... 8 more Caused by: com.microsoft.azure.servicebus.ServiceBusException: The message container is being closed (428). TrackingId:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_B24, SystemTracker:NoSystemTracker, Timestamp:12/18/2017 10:44:58 AM, errorContext[NS: xxxxxxxxxx.servicebus.windows.net, PATH: uploadnotifications/ConsumerGroups/kafka-cg/Partitions/1, REFERENCE_ID: xxxxxx_xxx_xxx_xxxxxxxxxxxxx, PREFETCH_COUNT: 999, LINK_CREDIT: 999, PREFETCH_Q_LEN: 0] at com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:60) at com.microsoft.azure.servicebus.MessageReceiver.onClose(MessageReceiver.java:587) at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:75) at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:46) at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309) at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276) at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:375) ... 1 more ",
      "id": 1,
      "worker_id": "connect-2.connect:28082"
    }
  ]
}
```

This second one is from a connector that is connected to a different EventHub resource. It has encountered a different error: **Exception - com.microsoft.azure.servicebus.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation.**
```js
{
  "name": "uploadnotifications_in",
  "connector": {
    "state": "RUNNING",
    "worker_id": "connect-2.connect:28082"
  },
  "tasks": [
    {
      "state": "RUNNING",
      "id": 0,
      "worker_id": "connect-0.connect:28082"
    },
    {
      "state": "FAILED",
      "trace": "org.apache.kafka.connect.errors.ConnectException: Error while polling for data at com.microsoft.azure.iot.kafka.connect.IotHubSourceTask.poll(IotHubSourceTask.scala:37) at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: org.apache.kafka.connect.errors.ConnectException: Error while getting SourceRecords for partition 13. Exception - com.microsoft.azure.servicebus.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_G4, SystemTracker:gateway6, Timestamp:12/18/2017 6:09:02 AM, errorContext[NS: xxxxxxxxxxxxxxx.servicebus.windows.net, PATH: uploadnotifications/ConsumerGroups/kafka-cg/Partitions/13, REFERENCE_ID: xxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_G4, PREFETCH_COUNT: 999, LINK_CREDIT: 0, PREFETCH_Q_LEN: 0, R_TYPE: NON_EPOCH] Stack trace - () at com.microsoft.azure.iot.kafka.connect.IotHubPartitionSource.getRecords(IotHubPartitionSource.scala:51) at com.microsoft.azure.iot.kafka.connect.IotHubSourceTask$$anonfun$poll$1.apply(IotHubSourceTask.scala:30) at com.microsoft.azure.iot.kafka.connect.IotHubSourceTask$$anonfun$poll$1.apply(IotHubSourceTask.scala:28) at scala.collection.immutable.List.foreach(List.scala:381) at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45) at com.microsoft.azure.iot.kafka.connect.IotHubSourceTask.poll(IotHubSourceTask.scala:28) ... 8 more Caused by: com.microsoft.azure.servicebus.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_G4, SystemTracker:gateway6, Timestamp:12/18/2017 6:09:02 AM, errorContext[NS: xxxxxxxxxxxxxxx.servicebus.windows.net, PATH: uploadnotifications/ConsumerGroups/kafka-cg/Partitions/13, REFERENCE_ID: xxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_G4, PREFETCH_COUNT: 999, LINK_CREDIT: 0, PREFETCH_Q_LEN: 0, R_TYPE: NON_EPOCH] at com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:58) at com.microsoft.azure.servicebus.MessageReceiver.onError(MessageReceiver.java:393) at com.microsoft.azure.servicebus.MessageReceiver.onClose(MessageReceiver.java:646) at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:83) at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:52) at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309) at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276) at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:340) ... 1 more Caused by: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_G4, SystemTracker:gateway6, Timestamp:12/18/2017 6:09:02 AM ... 11 more ",
      "id": 1,
      "worker_id": "connect-2.connect:28082"
    }
  ]
}
```
We think the first failure above is related to this [issue](https://github.com/Azure/azure-event-hubs/issues/320) where the Azure microservice that is hosting the eventhub needs to restart, thus disconnecting the receivers. Is it possible to try to handle these disconnects from the eventhub in this source connector? Or is it better to handle this in the azure-event-hubs library?

Our current approach is to monitor the connector status endpoints with a separate system and restart the connectors and tasks when necessary but I'm wondering if there is a better way.

For the record, we're connecting directly to a separate eventhub, not the actual IoTHub. We're doing this because we're routing some specific device message types to different custom endpoints in IoTHub, and those endpoints are backed by eventhubs. It's these eventhubs that we're connecting to with Kafka-connect. I'm not sure if that matters at all.

**Comment by gdooper** [comment]
As an update, I filed a support ticket to Azure Help + support, referencing the TrackingId provided in the error response. This was the response from the Azure Support Professional who was helping me:

_That container closing error is intermittent and expected when a container closes on one node as part of load balancing on the service or during upgrades. Those failures should not affect the receive functionality and should not block receivers. The container is our messaging container. As part of the load balancing logic containers move from one node to another. Original node closes the container before move. So clients observe this failure until container is available on another node. This should not take more than 20 seconds on average 10 seconds._
 
_Normally this transient exceptions will be handled by our clients retry mechanism: https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-event-hubs-retry-guidelines  ._
