### ISSUE TITLE
Issues with the Kafka Connect plugin for azure iot hub source connector

### ISSUE THREAD

**Issue by sriramakusu** [Azure/toketi-kafka-connect-iothub#29]
Upon following the instructions specified in the Kafka Connect plugin for Azure IoTHub source i.e., prepared the properties file and placed in the config directory and placed the JAR file of azure IoT hub in the lib directory.

When both the zookeeper and Kafka servers are running, I ran the following command:
bin/connect-standalone.sh config/connect-standalone.properties config/connect-iothub-source.properties

The command when ran is giving following error messages... Not sure if Microsoft is supporting this feature of Kafka Connect for IoTHub...

ERROR Plugin class loader for connector: 'com.microsoft.azure.iot.kafka.connect.IotHubSourceConnector' was not found. Returning: org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader@423e4cbb

ERROR WorkerSourceTask{id=AzureIotHubConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)

ERROR WorkerSourceTask{id=AzureIotHubConnector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)

[2020-04-14 16:05:31,694] ERROR WorkerSourceTask{id=AzureIotHubConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
com.microsoft.azure.servicebus.CommunicationException: java.nio.channels.UnresolvedAddressException. This is usually caused by incorrect hostname or network configuration. Please check to see if namespace information is correct. TrackingId: 16cca8fa-bb21-4c4c-84d7-6695f20de2ac, at: 2020-04-14T16:05:31.692+05:30[Asia/Kolkata]
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:371)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleBound(IOHandler.java:155)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:372)
	at org.apache.qpid.proton.engine.BaseHandler.onConnectionBound(BaseHandler.java:58)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:340)
	... 1 more

Can someone help me in understanding what exactly going wrong...?

**Comment by gurubaksh** [comment]
is this issue resolved i am facing same issue
